### ISSUE TITLE
HikariDataPool may produce ClassCastException when vertx-jooq.yml config as follows:

### ISSUE THREAD

**Issue by nutsjian** [silentbalanceyh/vertx-zero#304]
```yaml
jooq:
  provider:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hostname: database.0coolvertx0.io
    instance: DB_ETERNAL
    jdbcUrl: jdbc:mysql://database.0coolvertx0.io:3306/DB_ETERNAL
    options:
      hikari.max.lifetime: 25600000
      hikari.minimum.idle: 2
      hikari.maximum.pool.size: 8
```

line：70
this.dataSource.setMaxLifetime(this.database.getOption(OPT_MAX_LIFETIME, 25600000L));

hikari.max.lifetime：java.lang.Integer cannot be cast to class java.lang.Long
